### ISSUE TITLE
PyPI

### ISSUE THREAD

**Issue by rochacbruno** [ziplokk1/python-shopify-api#3]
@ziplokk1 to be able to deploy the code I had to deploy the module to PyPI (my host only installs source from PyPI)

https://pypi.python.org/pypi/python-shopify/

I want to transfer you the ownership of the module in PyPI, what is your pypi username?

Thanks

**Comment by ziplokk1** [comment]
@rochacbruno My username is `ziplokk`.

Thank you,
Mark

**Comment by rochacbruno** [comment]
Done! check if you got PyPI access and notification

**Comment by ziplokk1** [comment]
@rochacbruno Got it. Thanks!
